### ISSUE TITLE
Call the API to get data and print it in console.

### ISSUE THREAD

**Issue by utkarsh-1905** [MicrosoftStudentChapter/ISS-Tracker#1]
You have to use this api => [Where the ISS at?](https://wheretheiss.at/w/developer) and console log the data received in a readable format.
You can ask for hints below...

**Comment by saksham-tiwari** [comment]
@utkarsh-1905  I would like to work on this issue . Can you assign this to me?

**Comment by abhinandanwadwa** [comment]
Hey @utkarsh-1905, can you assign this issue to me?

**Comment by utkarsh-1905** [comment]
@saksham-tiwari  Create a function for calling the API, it should return the altitude, speed, latitude and longitude of ISS and print it to console.

Do ask for help if needed

**Comment by utkarsh-1905** [comment]
State your deadline too, else it will pass on to next person @saksham-tiwari

**Comment by saksham-tiwari** [comment]
> @saksham-tiwari Create a function for calling the API, it should return the altitude, speed, latitude and longitude of ISS and print it to console.
> 
> Do ask for help if needed

ok will do it by tomorrow.

**Comment by abhinandanwadwa** [comment]
My Deadline is 1-2 hours

**Comment by utkarsh-1905** [comment]
> Hey @utkarsh-1905, can you assign this issue to me?

Issues will assigned on first come first serve basis only, do check the other issues in the meantime

**Comment by saksham-tiwari** [comment]
Ok can do it in an hour. It is a simple task.

**Comment by saksham-tiwari** [comment]
> @saksham-tiwari Create a function for calling the API, it should return the altitude, speed, latitude and longitude of ISS and print it to console.
> 
> Do ask for help if needed

@utkarsh-1905 only thse 4 attributes are to be returned or something else too?

**Comment by saksham-tiwari** [comment]
Hey @utkarsh-1905, I have opened a pull request regarding this issue, pls have a look.

**Comment by utkarsh-1905** [comment]
Nice work @saksham-tiwari , PR merged
