### ISSUE TITLE
Add a pointer to the map based on a location.

### ISSUE THREAD

**Issue by utkarsh-1905** [MicrosoftStudentChapter/ISS-Tracker#5]
Create a function to add a pointer on the map taking lattitude/longitude as parameters.

Example- 
function addPointer(lat,long){
...
}

**Comment by abhinandanwadwa** [comment]
Can you explain this issue a little bit? @utkarsh-1905

**Comment by abhinandanwadwa** [comment]
@utkarsh-1905 I want to work on this issue. Can you assign it to me?

**Comment by abhinandanwadwa** [comment]
@utkarsh-1905 Done with the issue. Do check for other things to add (if any)
