### ISSUE TITLE
Change the default pointer icon to ISS png image

### ISSUE THREAD

**Issue by utkarsh-1905** [MicrosoftStudentChapter/ISS-Tracker#7]
Change the default map pointer (refer to leaflet.js docs) to ISS image (approx. 15*15px)

**Comment by lonewolf2208** [comment]
@utkarsh-1905 I would like to work on this issue . Can you assign this to me?

**Comment by utkarsh-1905** [comment]
> @utkarsh-1905 I would like to work on this issue . Can you assign this to me?

Ok, but you first need to add a pointer and then change its image, do ask for help if needed

**Comment by lonewolf2208** [comment]
Hey @utkarsh-1905 , adding the pointer corresponds to the issue #5

**Comment by utkarsh-1905** [comment]
Add a temporary one to change the image, then remove it

**Comment by lonewolf2208** [comment]
Hey @utkarsh-1905 can you also add the label hacktoberfest-accepted .
